web:
    image: wordpress
    links:
     - mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
     - WORDPRESS_DB_USER='root'
     - WORDPRESS_DB_NAME='my-wpdb'
     - WORDPRESS_DEBUG=1
    ports:
     - "127.0.0.3:8080:80"
    volumes:
        - "./plugins:/var/www/html/wp-content/plugins"
        - "./themes:/var/www/html/wp-content/themes/"
  
mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE='my-wpdb'
    ports:
        - 18766:3306
