version: '3'
services:
    web:
        image: wordpress
        links:
            - mysql
        environment:
            - WORDPRESS_DB_PASSWORD=password
            - WORDPRESS_DB_USER='root'
            - WORDPRESS_DB_NAME=wpdb
            - WORDPRESS_DEBUG=1
        networks:
            - wordpress
        ports:
            - "127.0.0.1:80:80"
        volumes:
            - "./plugins:/var/www/html/wp-content/plugins"
            - "./themes:/var/www/html/wp-content/themes/"
        depends_on:
            - mysql

    mysql:
        image:  mariadb:10.4
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=wpdb
        networks:
            - wordpress
        volumes:
            - 'mariadb:/var/lib/mysql'
        ports:
            - 1876:3306


networks:
    wordpress:
        driver: bridge


volumes:
    mariadb:
        driver: local